
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args:
        - --ignore=D100,D203,D212,D405,D401

  - repo: local
    hooks:
    -   id: run-tests
        name: run tests
        entry: pytest tests
        language: python
        always_run: true
        pass_filenames: false

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args: [--max-line-length=100]
        additional_dependencies: [pep8-naming]